# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matatuapp', '0002_auto_20160920_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='departing_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
