# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matatuapp', '0005_auto_20160920_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='departing_time',
            field=models.CharField(choices=[('6.00 AM', '6.00 AM'), ('8.00 AM', '8.00 AM'), ('10.00 AM', '10.00 AM'), ('12.00 PM', '12.00 AM'), ('3.00 PM', '3.00 PM'), ('4.00 PM', '4.00 PM'), ('6.00 PM', '6.00 PM'), ('8.00 PM', '8.00 PM'), ('10.00 PM', '10.00 PM')], max_length=8),
        ),
    ]
