# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matatuapp', '0006_auto_20160920_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_category',
            field=models.CharField(choices=[('14 Seater', '14 Seater'), ('Mini-Bus', 'Mini-Bus'), ('Bus', 'Bus')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
