# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matatuapp', '0007_vehicle_vehicle_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='available_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='passager',
            name='national_id',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
