# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 20:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('matatuapp', '0008_auto_20160920_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date_booked',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 20, 20, 38, 33, 669637, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
