# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matatuapp', '0010_parcel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcel',
            old_name='owner_full_name',
            new_name='sender_full_name',
        ),
        migrations.RenameField(
            model_name='parcel',
            old_name='owner_national_id',
            new_name='sender_national_id',
        ),
        migrations.RenameField(
            model_name='parcel',
            old_name='owner_phone_no',
            new_name='sender_phone_no',
        ),
    ]
